strict-sigcheck = false

[Google-Photos]
enabled = true
brand = "rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
changelog-keywords = ["Photos"]

[Google-Photos.patches]
"github:rushiranpise/morphe-patches" = []
